# ===== svc/dpn-kafka-target =====
apiVersion: v1
kind: Service
metadata:
  name: dpn-kafka-target
  namespace: ns-dpn-01
spec:
  ports:
  - name: kafka
    port: 9092
    protocol: TCP
    targetPort: 9092
  selector:
    app: dpn-kafka-target
  type: ClusterIP
